language: python
services:
    - mysql
before_install:
    - mysql -u root < tests/creat_data.sls 
    - cd tests
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install bs4 
  - pip install mysql-connector
script: 
    pytest;
    coverage run test_basic.py
after_success:
  - coveralls
