-- MySQL Script generated by MySQL Workbench
-- Sun Jun 10 18:18:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wnba_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wnba_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wnba_test` DEFAULT CHARACTER SET utf8 ;
USE `wnba_test` ;

-- -----------------------------------------------------
-- Table `wnba_test`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wnba_test`.`dates` (
  `iddates` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  PRIMARY KEY (`iddates`),
  UNIQUE INDEX `date_UNIQUE` (`date` ASC),
  INDEX `date_string` (`date` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wnba_test`.`box_score_urls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wnba_test`.`box_score_urls` (
  `idboxScoreUrls` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NULL DEFAULT NULL,
  `dateID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idboxScoreUrls`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  INDEX `boxScoreDateFK_idx` (`dateID` ASC),
  CONSTRAINT `boxScoreDateFK`
    FOREIGN KEY (`dateID`)
    REFERENCES `wnba_test`.`dates` (`iddates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wnba_test`.`player_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wnba_test`.`player_reference` (
  `playerID` INT(11) NOT NULL AUTO_INCREMENT,
  `bbrefID` TEXT NULL DEFAULT NULL,
  `rotogrindersID` INT(11) NULL DEFAULT NULL,
  `fanduelID` TEXT NULL DEFAULT NULL,
  `draftkingsID` INT(11) NULL DEFAULT NULL,
  `rotowireID` INT(11) NULL DEFAULT NULL,
  `firstName` VARCHAR(100) NULL DEFAULT NULL,
  `lastName` VARCHAR(100) NULL DEFAULT NULL,
  `playerName` VARCHAR(100) NULL DEFAULT NULL,
  `team` VARCHAR(45) NULL DEFAULT NULL,
  `pos` VARCHAR(45) NULL DEFAULT NULL,
  `nickName` VARCHAR(150) NULL DEFAULT NULL,
  `rotoguruID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`playerID`),
  UNIQUE INDEX `playerid_UNIQUE` (`playerID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wnba_test`.`performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wnba_test`.`performance` (
  `performanceID` INT(11) NOT NULL AUTO_INCREMENT,
  `playerID` INT(11) NULL DEFAULT NULL,
  `dateID` INT(11) NULL DEFAULT NULL,
  `blocks` INT(11) NULL DEFAULT NULL,
  `points` INT(11) NULL DEFAULT NULL,
  `steals` INT(11) NULL DEFAULT NULL,
  `assists` INT(11) NULL DEFAULT NULL,
  `turnovers` INT(11) NULL DEFAULT NULL,
  `totalRebounds` INT(11) NULL DEFAULT NULL,
  `tripleDouble` INT(11) NULL DEFAULT NULL,
  `doubleDouble` INT(11) NULL DEFAULT NULL,
  `fanduel` INT(11) NULL DEFAULT NULL,
  `draftkings` INT(11) NULL DEFAULT NULL,
  `3PM` INT(11) NULL DEFAULT NULL,
  `offensiveRebounds` INT(11) NULL DEFAULT NULL,
  `defensiveRebounds` FLOAT NULL DEFAULT NULL,
  `minutesPlayed` FLOAT NULL DEFAULT NULL,
  `fieldGoals` INT(11) NULL DEFAULT NULL,
  `fieldGoalsAttempted` INT(11) NULL DEFAULT NULL,
  `fieldGoalPercent` FLOAT NULL DEFAULT NULL,
  `3PA` INT(11) NULL DEFAULT NULL,
  `3PPercent` FLOAT NULL DEFAULT NULL,
  `FT` INT(11) NULL DEFAULT NULL,
  `FTA` INT(11) NULL DEFAULT NULL,
  `FTPercent` FLOAT NULL DEFAULT NULL,
  `personalFouls` INT(11) NULL DEFAULT NULL,
  `plusMinus` INT(11) NULL DEFAULT NULL,
  `trueShootingPercent` FLOAT NULL DEFAULT NULL,
  `effectiveFieldGoalPercent` FLOAT NULL DEFAULT NULL,
  `3pointAttemptRate` FLOAT NULL DEFAULT NULL,
  `freeThrowAttemptRate` FLOAT NULL DEFAULT NULL,
  `offensiveReboundPercent` FLOAT NULL DEFAULT NULL,
  `defensiveReboundPercent` FLOAT NULL DEFAULT NULL,
  `totalReboundPercent` FLOAT NULL DEFAULT NULL,
  `assistPercent` FLOAT NULL DEFAULT NULL,
  `stealPercent` FLOAT NULL DEFAULT NULL,
  `blockPercent` FLOAT NULL DEFAULT NULL,
  `turnoverPercent` FLOAT NULL DEFAULT NULL,
  `usagePercent` FLOAT NULL DEFAULT NULL,
  `offensiveRating` INT(11) NULL DEFAULT NULL,
  `defensiveRating` INT(11) NULL DEFAULT NULL,
  `team` VARCHAR(45) NULL DEFAULT NULL,
  `opponent` VARCHAR(45) NULL DEFAULT NULL,
  `home` INT(11) NULL DEFAULT NULL,
  `fanduelPosition` VARCHAR(45) NULL DEFAULT NULL,
  `draftkingsPosition` VARCHAR(45) NULL DEFAULT NULL,
  `fanduelPts` FLOAT NULL DEFAULT '0',
  `draftkingsPts` FLOAT NULL DEFAULT NULL,
  `simmonsProj` FLOAT NULL DEFAULT NULL,
  `zoProj` FLOAT NULL DEFAULT NULL,
  `hardawayProj` FLOAT NULL DEFAULT NULL,
  `leProj` FLOAT NULL DEFAULT NULL,
  `projMinutes` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`performanceID`),
  INDEX `performanceDate_idx` (`dateID` ASC),
  INDEX `playerPerformance_idx` (`playerID` ASC),
  CONSTRAINT `datePerformance`
    FOREIGN KEY (`dateID`)
    REFERENCES `wnba_test`.`dates` (`iddates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `playerPerformance`
    FOREIGN KEY (`playerID`)
    REFERENCES `wnba_test`.`player_reference` (`playerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wnba_test`.`team_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wnba_test`.`team_reference` (
  `teamID` int(10) NOT NULL AUTO_INCREMENT,
  `bbreff` varchar(100) DEFAULT NULL,
  `wsa` varchar(45) DEFAULT NULL,
  `fanduel` varchar(45) DEFAULT NULL,
  `rotowire` varchar(45) DEFAULT NULL,
  `bovada` varchar(45) DEFAULT NULL,
  `City` varchar(45) DEFAULT NULL,
  `Name` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`teamID`),
  UNIQUE KEY `wsp_UNIQUE` (`wsa`),
  UNIQUE KEY `bbreff_UNIQUE` (`bbreff`),
  UNIQUE KEY `fanduel_UNIQUE` (`fanduel`),
  UNIQUE KEY `rotowire_UNIQUE` (`rotowire`),
  UNIQUE KEY `bovada_UNIQUE` (`bovada`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- -----------------------------------------------------
-- Table `wnba_test`.`team_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wnba_test`.`team_performance` (
  `teamPerformanceID` int(11) NOT NULL AUTO_INCREMENT,
  `dailyTeamID` int(11) DEFAULT NULL,
  `dailyTeamOpponentID` int(11) DEFAULT NULL,
  `dateID` int(11) DEFAULT NULL,
  `pointsAllowed` float DEFAULT NULL,
  `pointsScored` float DEFAULT NULL,
  `pace` float DEFAULT NULL,
  `effectiveFieldGoalPercent` float DEFAULT NULL,
  `turnoverPercent` float DEFAULT NULL,
  `FTperFGA` float DEFAULT NULL,
  `offensiveRating` float DEFAULT NULL,
  `defensiveRating` float DEFAULT NULL,
  `FG` int(11) DEFAULT NULL,
  `FGA` int(11) DEFAULT NULL,
  `FGP` float DEFAULT NULL,
  `3P` int(11) DEFAULT NULL,
  `3PA` int(11) DEFAULT NULL,
  `3PP` float DEFAULT NULL,
  `FT` int(11) DEFAULT NULL,
  `FTA` int(11) DEFAULT NULL,
  `FTP` float DEFAULT NULL,
  `offensiveRebounds` int(11) DEFAULT NULL,
  `defensiveRebounds` int(11) DEFAULT NULL,
  `totalRebounds` int(11) DEFAULT NULL,
  `assists` int(11) DEFAULT NULL,
  `steals` int(11) DEFAULT NULL,
  `blocks` int(11) DEFAULT NULL,
  `turnovers` int(11) DEFAULT NULL,
  `personalFouls` int(11) DEFAULT NULL,
  `trueShootingPercent` float DEFAULT NULL,
  `3pointAttemptRate` float DEFAULT NULL,
  `freeThrowAttemptRate` float DEFAULT NULL,
  `defensiveReboundPercent` float DEFAULT NULL,
  `offensiveReboundPercent` float DEFAULT NULL,
  `totalReboundPercent` float DEFAULT NULL,
  `assistPercent` float DEFAULT NULL,
  `stealPercent` float DEFAULT NULL,
  `blockPercent` float DEFAULT NULL,
  `win` int(11) DEFAULT NULL,
  `loss` int(11) DEFAULT NULL,
  `points1Q` float DEFAULT NULL,
  `points2Q` float DEFAULT NULL,
  `points3Q` float DEFAULT NULL,
  `points4Q` float DEFAULT NULL,
  PRIMARY KEY (`teamPerformanceID`),
  KEY `dailyTeamP_idx` (`dailyTeamID`),
  KEY `dailyTeamOppP_idx` (`dailyTeamOpponentID`),
  CONSTRAINT `dailyTeamOppP` FOREIGN KEY (`dailyTeamOpponentID`) REFERENCES `team_reference` (`teamID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `dailyTeamP` FOREIGN KEY (`dailyTeamID`) REFERENCES `team_reference` (`teamID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `wnba_test`.`player_daily_avg` (
  `iddailyplayer` int(11) NOT NULL AUTO_INCREMENT,                                                                                                                                       
  `playerID` int(11) DEFAULT NULL,                                                                                                                                                       
  `dateID` int(11) DEFAULT NULL,                                                                                                                                                         
  `blocks` float DEFAULT NULL,                                                                                                                                                           
  `points` float DEFAULT NULL,                                                                                                                                                           
  `steals` float DEFAULT NULL,
  `AST` float DEFAULT NULL,
  `turnovers` float DEFAULT NULL,
  `totalRebounds` float DEFAULT NULL,
  `tripleDouble` float DEFAULT NULL,
  `doubleDouble` float DEFAULT NULL,
  `3PM` float DEFAULT NULL,
  `oRebound` float DEFAULT NULL,
  `dRebound` float DEFAULT NULL,
  `minutes` float DEFAULT NULL,
  `FG` float DEFAULT NULL,
  `FGA` float DEFAULT NULL,
  `FGP` float DEFAULT NULL,
  `3PA` float DEFAULT NULL,
  `3PP` float DEFAULT NULL,
  `FTM` float DEFAULT NULL,
  `FTA` float DEFAULT NULL,
  `FTP` float DEFAULT NULL,
  `personalFouls` float DEFAULT NULL,
  `plusMinus` float DEFAULT NULL,
  `trueShootingP` float DEFAULT NULL,
  `eFG` float DEFAULT NULL,
  `freeThrowAttemptRate` float DEFAULT NULL,
  `3PointAttemptRate` float DEFAULT NULL,
  `oReboundP` float DEFAULT NULL,
  `dReboundP` float DEFAULT NULL,
  `totalReboundP` float DEFAULT NULL,
  `ASTP` float DEFAULT NULL,
  `STP` float DEFAULT NULL,
  `BLKP` float DEFAULT NULL,
  `turnoverP` float DEFAULT NULL,
  `USG` float DEFAULT NULL,
  `oRating` float DEFAULT NULL,
  `dRating` float DEFAULT NULL,
  PRIMARY KEY (`iddailyplayer`),
  KEY `playerDailyData_idx` (`playerID`),
  KEY `playerDailyDateID_idx` (`dateID`),
  CONSTRAINT `playerDailyDataPlayerID` FOREIGN KEY (`playerID`) REFERENCES `player_reference` (`playerID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `playerDailyDateID` FOREIGN KEY (`dateID`) REFERENCES `dates` (`iddates`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `wnba_test`.`team_daily_avg_performance` (
  `dailyAvgPerformanceID` int(11) NOT NULL AUTO_INCREMENT,                                                                                                                               
  `dailyTeamID` int(11) DEFAULT NULL,                                                                                                                                                    
  `dateID` int(11) DEFAULT NULL,                                                                                                                                                         
  `wins` int(11) DEFAULT NULL,                                                                                                                                                           
  `losses` int(11) DEFAULT NULL,                                                                                                                                                         
  `ORT` float DEFAULT NULL,                                                                                                                                                              
  `DRT` float DEFAULT NULL,                                                                                                                                                              
  `avgPointsAllowed` float DEFAULT NULL,                                                                                                                                                 
  `avgPointsScored` float DEFAULT NULL,                                                                                                                                                  
  `pace` float DEFAULT NULL,                                                                                                                                                             
  `effectiveFieldGoalPercent` float DEFAULT NULL,                                                                                                                                        
  `turnoverPercent` float DEFAULT NULL,
  `offensiveReboundPercent` float DEFAULT NULL,
  `FT/FGA` float DEFAULT NULL,
  `FG` float DEFAULT NULL,
  `FGA` float DEFAULT NULL,
  `FGP` float DEFAULT NULL,
  `3P` float DEFAULT NULL,
  `3PA` float DEFAULT NULL,
  `3PP` float DEFAULT NULL,
  `FT` float DEFAULT NULL,
  `FTA` float DEFAULT NULL,
  `FTP` float DEFAULT NULL,
  `offensiveRebounds` float DEFAULT NULL,
  `defensiveRebounds` float DEFAULT NULL,
  `totalRebounds` float DEFAULT NULL,
  `assists` float DEFAULT NULL,
  `steals` float DEFAULT NULL,
  `blocks` float DEFAULT NULL,
  `turnovers` float DEFAULT NULL,
  `personalFouls` float DEFAULT NULL,
  `trueShootingPercent` float DEFAULT NULL,
  `3pointAttemptRate` float DEFAULT NULL,
  `freeThrowAttemptRate` float DEFAULT NULL,
  `defensiveReboundPercent` float DEFAULT NULL,
  `totalReboundPercent` float DEFAULT NULL,
  `assistPercent` float DEFAULT NULL,
  `stealPercent` float DEFAULT NULL,
  `blockPercent` float DEFAULT NULL,
  `points1Q` float DEFAULT NULL,
  `points2Q` float DEFAULT NULL,
  `points3Q` float DEFAULT NULL,
  `points4Q` float DEFAULT NULL,
  PRIMARY KEY (`dailyAvgPerformanceID`),
  KEY `dailyTeamPerformanceTeamID_idx` (`dailyTeamID`),
  KEY `dailyTeamPerformanceDateID_idx` (`dateID`),
  CONSTRAINT `dailyTeamPerformanceDateID` FOREIGN KEY (`dateID`) REFERENCES `dates` (`iddates`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `dailyTeamPerformanceTeamID` FOREIGN KEY (`dailyTeamID`) REFERENCES `team_reference` (`teamID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `wnba_test`.`team_vs_guards` (
  `teamID` int(11) NOT NULL AUTO_INCREMENT,                                                                                                                                              
  `dailyTeamID` int(11) NOT NULL,                                                                                                                                                        
  `dateID` int(11) NOT NULL,
  `blocks` int(11) DEFAULT NULL,
  `points` int(11) DEFAULT NULL,
  `steals` int(11) DEFAULT NULL,
  `assists` int(11) DEFAULT NULL,
  `turnovers` int(11) DEFAULT NULL,
  `tRebounds` int(11) DEFAULT NULL,
  `DDD` int(11) DEFAULT NULL,
  `DD` int(11) DEFAULT NULL,
  `3PM` int(11) DEFAULT NULL,
  `3PA` int(11) DEFAULT NULL,
  `oRebounds` int(11) DEFAULT NULL,
  `dRebounds` int(11) DEFAULT NULL,
  `minutes` float DEFAULT NULL,
  `FG` int(11) DEFAULT NULL,
  `FGA` int(11) DEFAULT NULL,
  `FT` int(11) DEFAULT NULL,
  `FTA` int(11) DEFAULT NULL,
  `BPM` float DEFAULT NULL,
  `PPM` float DEFAULT NULL,
  `SPM` float DEFAULT NULL,
  `APM` float DEFAULT NULL,
  `TPM` float DEFAULT NULL,
  `DDDPG` float DEFAULT NULL,
  `DDPG` float DEFAULT NULL,
  `3PP` float DEFAULT NULL,
  `ORPM` float DEFAULT NULL,
  `DRPM` float DEFAULT NULL,
  `FGP` float DEFAULT NULL,
  `FTP` float DEFAULT NULL,
  `usg` float DEFAULT NULL,
  `ORT` float DEFAULT NULL,
  `DRT` float DEFAULT NULL,
  `TS` float DEFAULT NULL,
  `eFG` float DEFAULT NULL,
  PRIMARY KEY (`teamID`),
  KEY `guardsTeamID_idx` (`dailyTeamID`),
  KEY `guardsDateID_idx` (`dateID`),
  CONSTRAINT `guardsDateID` FOREIGN KEY (`dateID`) REFERENCES `dates` (`iddates`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `guardsTeamID` FOREIGN KEY (`dailyTeamID`) REFERENCES `team_reference` (`teamID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `wnba_test`.`team_vs_fowards` (
  `teamID` int(11) NOT NULL AUTO_INCREMENT,                                                                                                                                              
  `dailyTeamID` int(11) NOT NULL,                                                                                                                                                        
  `dateID` int(11) NOT NULL,
  `blocks` int(11) DEFAULT NULL,
  `points` int(11) DEFAULT NULL,
  `steals` int(11) DEFAULT NULL,
  `assists` int(11) DEFAULT NULL,
  `turnovers` int(11) DEFAULT NULL,
  `tRebounds` int(11) DEFAULT NULL,
  `DDD` int(11) DEFAULT NULL,
  `DD` int(11) DEFAULT NULL,
  `3PM` int(11) DEFAULT NULL,
  `3PA` int(11) DEFAULT NULL,
  `oRebounds` int(11) DEFAULT NULL,
  `dRebounds` int(11) DEFAULT NULL,
  `minutes` float DEFAULT NULL,
  `FG` int(11) DEFAULT NULL,
  `FGA` int(11) DEFAULT NULL,
  `FT` int(11) DEFAULT NULL,
  `FTA` int(11) DEFAULT NULL,
  `BPM` float DEFAULT NULL,
  `PPM` float DEFAULT NULL,
  `SPM` float DEFAULT NULL,
  `APM` float DEFAULT NULL,
  `TPM` float DEFAULT NULL,
  `DDDPG` float DEFAULT NULL,
  `DDPG` float DEFAULT NULL,
  `3PP` float DEFAULT NULL,
  `ORPM` float DEFAULT NULL,
  `DRPM` float DEFAULT NULL,
  `FGP` float DEFAULT NULL,
  `FTP` float DEFAULT NULL,
  `usg` float DEFAULT NULL,
  `ORT` float DEFAULT NULL,
  `DRT` float DEFAULT NULL,
  `TS` float DEFAULT NULL,
  `eFG` float DEFAULT NULL,
  PRIMARY KEY (`teamID`),
  KEY `fowardsTeamID_idx` (`dailyTeamID`),
  KEY `fowardsDateID_idx` (`dateID`),
  CONSTRAINT `fowardsDateID` FOREIGN KEY (`dateID`) REFERENCES `dates` (`iddates`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fowardsTeamID` FOREIGN KEY (`dailyTeamID`) REFERENCES `team_reference` (`teamID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
